version: '3.4'
services:
  segment-management:
    image: segment-management
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - db
    ports:
      - 8082:8080
  db:
    image: postgres:15.3-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432
    networks:
      - backend
volumes:
  pgdata:
networks:
  backend:
    driver: bridge
