env: "dev"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
postgres:
  host: "localhost"
  port: "5436"
  username: "postgres"
  password: "qwerty"
  db_name: "postgres"
  ssl_mode: "disable"