env: "dev"
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s
postgres:
  host: "db"
  port: "5432"
  username: "postgres"
  password: "postgres"
  db_name: "postgres"
  ssl_mode: "disable"
ttl_checker_seconds: 20